name: 'eurostat_fiscal'
version: '1.0.0'

profile: 'eurostat_fiscal'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  eurostat_fiscal:
    +schema: eurostat
    +quote_columns: false

models:
  eurostat_fiscal:
    silver:
      +materialized: view
      +schema: eurostat
    gold:
      +materialized: view
      +schema: eurostat